### ISSUE TITLE
UnboundLocalError: local variable 'vocals3' referenced before assignment

### ISSUE THREAD

**Issue by changqingonly** [jarredou/MVSEP-MDX23-Colab_v2#18]
Traceback (most recent call last):
  File "/$path/mvsep_v2/inference.py", line 978, in <module>
    predict_with_model(options)
  File "/$path/mvsep_v2/inference.py", line 862, in predict_with_model
    result, sample_rates = model.separate_music_file(audio.T, sr, i, len(options['input_audio']))
  File "/$path/mvsep_v2/inference.py", line 699, in separate_music_file
    vocals_high = lr_filter(vocals3.T, 12000, 'highpass')
UnboundLocalError: local variable 'vocals3' referenced before assignment

branch: v2.4

**Comment by changqingonly** [comment]
> --use_InstVoc must be always set in command line if you're using directly inference.py without the related colab notebook. It is required whatever other model combination is chosen. InstVoc is used in all cases for high frequency band of the multiband ensemble. I'll add a safeguard for that for CLI usage (which I sometimes forget to fully test, as I'm using the notebook on Colab)

it's worked
