### ISSUE TITLE
I ran into a problem after trying to use all the models.

### ISSUE THREAD

**Issue by iPadian198** [jarredou/MVSEP-MDX23-Colab_v2#20]
Traceback (most recent call last):
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 1014, in <module>
    predict_with_model(options)
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 895, in predict_with_model
    result, sample_rates = model.separate_music_file(audio.T, sr, i, len(options['input_audio']))
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 694, in separate_music_file
    sources2 = 0.5 * demix_wrapper(
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 274, in demix_wrapper
    sources = demix(shifted_mix, device, models, infer_session, overlap) * vc # 1.021 volume compensation
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 334, in demix
    res = _ort.run(None, {'input': stft_res.cpu().numpy()})[0]
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running FusedConv node. Name:'Conv_16' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 62914560

**Comment by deton24** [comment]
Maybe try to use a shorter input file. Manipulating with big shifts and
overlap might help too, but I can't suggest any specific values (and
whether it will really use less memory for sure, but you could try).
Monitor VRAM usage in Environment during separation and experiment.

pt., 20 wrz 2024 o 03:12 iPadian198 ***@***.***> napisał(a):
