### ISSUE TITLE
Array size error

### ISSUE THREAD

**Issue by visvaldas01** [jarredou/MVSEP-MDX23-Colab_v2#21]
Getting an error when trying to split [this song](https://drive.google.com/file/d/1-2bR3Quy06_2vDmLYXPmlDEOpFuNtNKf) to vocals and instrumental.

/content/MVSEP-MDX23-Colab_v2
GPU use: 0
started!

Options: 
Input Gain: 0dB
Restore Gain: False
BigShifts: 3

BSRoformer_model: ep_368_1296
weight_BSRoformer: 9.18
weight_InstVoc: 3.39

use_VitLarge: False
use_VOCFT: False
use_InstHQ4: False
vocals_only: True
output_format: FLAC

Loading BS-Roformer into memory
Non-A100 GPU detected, using math or mem efficient attention if input tensor is on cuda
Loading Kim MelbandRoformer into memory
Loading InstVoc into memory
Go for: /content/drive/MyDrive/input
Traceback (most recent call last):
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 1014, in <module>
    predict_with_model(options)
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 886, in predict_with_model
    audio, sr = librosa.load(input_audio, mono=False, sr=44100)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 222, in __soundfile_load
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 891, in read
    out = self._create_empty_array(frames, always_2d, dtype)
  File "/usr/local/lib/python3.10/dist-packages/soundfile.py", line 1323, in _create_empty_array
    return np.empty(shape, dtype, order='C')
ValueError: array is too big; \`arr.size * arr.dtype.itemsize\` is larger than the maximum possible size.

**Comment by deton24** [comment]
That seems to be related to your input file.
1. It lacks .flac extension in the file name after I download it
2. It's detected in VLC to have 3 channels instead of two
3. It has seeking issues, and it doesn't detect total audio elapsed time

Convert it to WAV. If still the same, downmix to stereo and retry. Or
simply get the file from some other source.

niedz., 22 wrz 2024, 02:24 użytkownik visvaldas01 ***@***.***>
napisał:
